// <auto-generated />
using System;
using Bsd.Infrastructure.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Bsd.Infrastructure.Migrations
{
    [DbContext(typeof(BsdDbContext))]
    [Migration("20240707150300_NewMigration02")]
    partial class NewMigration02
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.4");

            modelBuilder.Entity("Bsd.Domain.Entities.BsdEntity", b =>
                {
                    b.Property<int>("BsdId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateService")
                        .HasColumnType("TEXT");

                    b.Property<int>("DayType")
                        .HasColumnType("INTEGER");

                    b.HasKey("BsdId");

                    b.ToTable("BsdEntities");
                });

            modelBuilder.Entity("Bsd.Domain.Entities.Employee", b =>
                {
                    b.Property<int>("EmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("BsdEntityBsdId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Digit")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ServiceType")
                        .HasColumnType("INTEGER");

                    b.HasKey("EmployeeId");

                    b.HasIndex("BsdEntityBsdId");

                    b.ToTable("Employee");
                });

            modelBuilder.Entity("Bsd.Domain.Entities.EmployeeRubricAssignment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("BsdEntityBsdId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("BsdEntityBsdId");

                    b.ToTable("EmployeeRubricAssignment");
                });

            modelBuilder.Entity("Bsd.Domain.Entities.Rubric", b =>
                {
                    b.Property<int>("RubricId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DayType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("EmployeeRubricAssignmentId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("HoursPerDay")
                        .HasColumnType("TEXT");

                    b.Property<int>("ServiceType")
                        .HasColumnType("INTEGER");

                    b.HasKey("RubricId");

                    b.HasIndex("EmployeeRubricAssignmentId");

                    b.ToTable("Rubric");
                });

            modelBuilder.Entity("Bsd.Domain.Entities.Employee", b =>
                {
                    b.HasOne("Bsd.Domain.Entities.BsdEntity", null)
                        .WithMany("Employees")
                        .HasForeignKey("BsdEntityBsdId");
                });

            modelBuilder.Entity("Bsd.Domain.Entities.EmployeeRubricAssignment", b =>
                {
                    b.HasOne("Bsd.Domain.Entities.BsdEntity", null)
                        .WithMany("EmployeeRubricAssignments")
                        .HasForeignKey("BsdEntityBsdId");
                });

            modelBuilder.Entity("Bsd.Domain.Entities.Rubric", b =>
                {
                    b.HasOne("Bsd.Domain.Entities.EmployeeRubricAssignment", null)
                        .WithMany("AllowedRubrics")
                        .HasForeignKey("EmployeeRubricAssignmentId");
                });

            modelBuilder.Entity("Bsd.Domain.Entities.BsdEntity", b =>
                {
                    b.Navigation("EmployeeRubricAssignments");

                    b.Navigation("Employees");
                });

            modelBuilder.Entity("Bsd.Domain.Entities.EmployeeRubricAssignment", b =>
                {
                    b.Navigation("AllowedRubrics");
                });
#pragma warning restore 612, 618
        }
    }
}
