name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4.0.0
        with:
          dotnet-version: '7.0.x'

      - name: Restore dependencies and build
        run: |
          dotnet restore
          dotnet build --configuration Release

      - name: Test
        id: test
        run: |
          dotnet test
