name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Restore dependencies and build
        run: |
          dotnet restore
          dotnet build --configuration Release

  test-unit:
    runs-on: ubuntu-latest
    env:
      SMARTCLOCK_API_URL: ${{ secrets.SMARTCLOCK_API_URL }}
      SMARTCLOCK_IDENTIFIER: ${{ secrets.SMARTCLOCK_IDENTIFIER }}
      SMARTCLOCK_TOKEN: ${{ secrets.SMARTCLOCK_TOKEN }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Restore dependencies
        run: dotnet restore Bsd.sln

      - name: Run Unit Tests
        run: dotnet test tests/Bsd.Tests.Unit/Bsd.Tests.Unit.csproj